language: python

python:
- "3.6"

install:
  - pip install -r requirements.txt

before_script: cd app

script:
  - python3 __init__.py || python __init__.py
  - flake8 --exclude=\.eggs,tests,docs --max-line-length 80 .
